main/urls.py
from django.urls import path

from main.views import (
    FacultyListView,
    DepartmentListView,
    DirectionsListView,
    PracticePlacesListView,
    UsersListView,
    AdminView,
    FacultyCreateView,
    DepartmentCreateView,
    DirectionCreateView,
    GroupCreateView,
    PracticePlaceCreateView, export_data,
)

from main.views import (
    get_departments,
    get_directions,
    get_practice_places,
    get_groups,
    user_create_view
)

app_name = 'main'

urlpatterns = [
    path('get_departments/', get_departments, name='get_departments'),
    path('get_directions/', get_directions, name='get_directions'),
    path('get_practice_places/', get_practice_places, name='get_practice_places'),
    path('get_groups/', get_groups, name='get_groups'),
    path('register/', user_create_view, name='user_create_view'),

    path('admin/', AdminView.as_view(), name='admin'),

    path('faculties/', FacultyListView.as_view(), name='faculties'),
    path('faculties/create/', FacultyCreateView.as_view(), name='faculty-create'),

    path('department/<int:pk>/', DepartmentListView.as_view(), name='departments'),
    path('department/create/', DepartmentCreateView.as_view(), name='department-create'),

    path('direction/<int:pk>/', DirectionsListView.as_view(), name='directions'),
    path('direction/create/', DirectionCreateView.as_view(), name='direction-create'),

    path('practice_places/<int:pk>/', PracticePlacesListView.as_view(), name='places'),
    path('group/create/', GroupCreateView.as_view(), name='group-create'),

    path('practice_place/<int:pk>/', UsersListView.as_view(), name='users'),
    path('practice_place/create/', PracticePlaceCreateView.as_view(), name='practice-create'),

    path('export/<int:pk>/', export_data, name='export-data')

]

practice_register/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('main/', include('main.urls', namespace='main')),
)

main/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _


class FacultyModel(models.Model):
    faculty_name = models.CharField(max_length=255, verbose_name=_('faculty_name'), db_index=True)
    abbreviation = models.CharField(max_length=30, verbose_name=_('abbreviation'), null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))

    def __str__(self):
        return self.faculty_name

    class Meta:
        verbose_name = _('faculty')
        verbose_name_plural = _('faculties')


class DepartmentModel(models.Model):
    dep_name = models.CharField(max_length=255, verbose_name=_('dep_name'), db_index=True)
    abbreviation = models.CharField(max_length=30, verbose_name=_('abbreviation'), null=True, blank=True)
    faculty = models.ForeignKey(
        FacultyModel,
        on_delete=models.CASCADE,
        related_name='departments',
        verbose_name=_('faculty')
    )

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))

    def __str__(self):
        return self.dep_name

    class Meta:
        verbose_name = _('department')
        verbose_name_plural = _('departments')


class DirectionModel(models.Model):
    direction_name = models.CharField(max_length=255, verbose_name=_('direction_name'), db_index=True)
    abbreviation = models.CharField(max_length=30, verbose_name=_('abbreviation'), null=True, blank=True)
    department = models.ForeignKey(
        DepartmentModel,
        on_delete=models.CASCADE,
        related_name='directions',
        verbose_name=_('department')
    )

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))

    def __str__(self):
        return self.abbreviation

    class Meta:
        verbose_name = _('direction')
        verbose_name_plural = _('directions')


class GroupModel(models.Model):
    number = models.CharField(max_length=5, verbose_name=_('number'), db_index=True)
    direction = models.ForeignKey(
        DirectionModel,
        on_delete=models.CASCADE,
        related_name='groups',
        verbose_name=_('direction')
    )

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))

    def __str__(self):
        return self.number

    class Meta:
        verbose_name = _('group')
        verbose_name_plural = _('groups')


class PracticePlaceModel(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('name'), db_index=True)
    abbreviation = models.CharField(max_length=30, verbose_name=_('abbreviation'), null=True, blank=True)
    phone_number = models.CharField(max_length=13, verbose_name=_('phone_number'))
    address = models.CharField(max_length=255, verbose_name=_('address'))
    target = models.CharField(max_length=100, verbose_name=_('target'))
    direction = models.ForeignKey(
        DirectionModel,
        on_delete=models.CASCADE,
        related_name='practice_places',
        verbose_name=_('department')
    )
    limit = models.PositiveIntegerField(verbose_name=_('limit'))

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('practice place')
        verbose_name_plural = _('practice places')


class UserModel(models.Model):
    first_name = models.CharField(max_length=30, verbose_name=_('first_name'), db_index=True)
    last_name = models.CharField(max_length=30, verbose_name=_('last_name'))
    faculty = models.ForeignKey(
        FacultyModel,
        on_delete=models.CASCADE,
        related_name='students',
        verbose_name=_('faculty')
    )
    department = models.ForeignKey(
        DepartmentModel,
        on_delete=models.CASCADE,
        related_name='students',
        verbose_name=_('department')
    )
    direction = models.ForeignKey(
        DirectionModel,
        on_delete=models.CASCADE,
        related_name='students',
        verbose_name=_('direction')
    )
    group = models.ForeignKey(
        GroupModel,
        on_delete=models.CASCADE,
        related_name='students',
        verbose_name=_('group')
    )
    practice_place = models.ForeignKey(
        PracticePlaceModel,
        on_delete=models.CASCADE,
        related_name='users',
        verbose_name=_('practice_place')
    )

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def save(self, *args, **kwargs):
        if self.pk is None:  # Only check limit when creating a new user
            place = self.practice_place
            if getattr(place, 'limit', None) is not None and place.users.count() >= place.limit:
                raise ValidationError('Practice place user limit reached.')
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

templates/admin.html
{% extends 'base.html' %}

{% block detail %}
    <div class="register-flex">
        <div class="register-div">
            <label> Fakultet Yaratish:
                <a href="{% url 'main:faculty-create' %}">
                    <button class="button-style button-style_register">
                        Fakultet Yaratish
                    </button>
                </a>
            </label>
        </div>
        <div class="register-div">
            <label> Kafedra Yaratish:
                <a href="{% url 'main:department-create' %}">
                    <button class="button-style button-style_register">
                        Kafedra Yaratish
                    </button>
                </a>
            </label>
        </div>
        <div class="register-div">
            <label> Yo'nalish Yaratish:
                <a href="{% url 'main:direction-create' %}">
                    <button class="button-style button-style_register">
                        Yo'nalish yaratish
                    </button>
                </a>
            </label>
        </div>
        <div class="register-div">
            <label> Guruh Yaratish:
                <a href="{% url 'main:group-create' %}">
                    <button class="button-style button-style_register">
                        Guruh Yaratish
                    </button>
                </a>
            </label>
        </div>
        <div class="register-div">
            <label> Amaliyot joyini yaratish:
                <a href="{% url 'main:practice-create' %}">
                    <button class="button-style button-style_register">
                        Amaliyot Joyini Yaratish
                    </button>
                </a>
            </label>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% trans 'Amaliyot tanlash' %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>

{% block detail %}{% endblock %}

{% block extra_js %}{% endblock %}
</body>
</html>

templates/department_create.html
{% extends 'base.html' %}

{% block detail %}
    <form class="form" method="POST">
        {% csrf_token %}
        <div class="form__center">
            <h1 class="h1-style">Kafedra Yaratish</h1>
            <div class="input-div">
               <label class="label-style">Kafedra nomi:
                <input class="input-style" type="text" required>
            </label>
            <label class="label-style">Qisqartmasi
                <input class="input-style" type="text">
            </label>
            <label>Fakultet:
                <select class="input-style" id="faculty" name="faculty" required>
                    {% for faculty in faculties %}
                        <option class="option" value="{{ faculty.id }}">{{ faculty.faculty_name }}</option>
                    {% endfor %}
                </select>
            </label>
            </div>


            <div class="button-div_register">
                <a href="{% url 'main:admin' %}">
                    <button class="button-style" type="button">
                        Orqaga
                    </button>
                </a>
                <button class="button-style" type="submit">
                    Yaratish
                </button>
            </div>
        </div>
    </form>
{% endblock %}

templates/departments.html
{% extends 'base.html' %}
{% load static %}

{% block detail %}
    <header class="header">
        <div class="container">
            <div class="navbar">
                <div class="navbar-logo">
                    <img class="img-style" src="{% static 'img/logo.svg' %}" alt="#">
                    <h1 class="logo-h1"><a href="{% url 'main:faculties' %}">"TIQXMMI" MTU</a></h1>
                </div>
            </div>
        </div>
    </header>
    <main class="main">
        <div class="container">
            <div class="main-style">
                <h1 class="h1-style">
                    Kafedralar
                </h1>
                <div class="table-div">
                    <table class="table-style">
                        {% for department in departments %}
                            <tr class="tr-style">
                                <td>
                                    {{ department.dep_name }}
                                </td>
                                <td>
                                    <a href="{% url 'main:directions' pk=department.pk %}">
                                        <button class="button-style">
                                            Ma'lumotlar
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}

                    </table>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/direction_create.html
{% extends 'base.html' %}

{% load static %}

{% block detail %}

    <form class="form" method="post">
        {% csrf_token %}
        <div class="form__center">
            <h1 class="h1-style">Yo'nalish yaratish</h1>
            <div class="input-div">
                <label class="label-style">Yo'nalish nomi:
                    <input class="input-style" type="text" name="direction_name" required>
                </label>
                <label class="label-style">Qisqartmasi
                    <input class="input-style" type="text" name="abbreviation">
                </label>

                <label class="label-style">Kafedra:
                    <select class="input-style" id="department" name="department" required>
                        {% for department in departments %}
                            <option class="option" value="{{ department.id }}">{{ department.dep_name }}</option>
                        {% endfor %}
                    </select>
                </label>
            </div>


            <div class="button-div_register">
                <a href="{% url 'main:admin' %}">
                    <button class="button-style" type="button">
                        Orqaga
                    </button>
                </a>
                <button class="button-style" type="submit">
                    Yaratish
                </button>
            </div>
        </div>
    </form>

{% endblock %}

templates/directions.html
{% extends 'base.html' %}
{% load static %}

{% block detail %}


    <header class="header">
        <div class="container">
            <div class="navbar">
                <div class="navbar-logo">
                    <img class="img-style" src="{% static 'img/logo.svg' %}" alt="'TIQXMMI' MTU logo">
                    <h1 class="logo-h1"><a href="{% url 'main:faculties' %}">"TIQXMMI" MTU</a></h1>
                </div>
            </div>
        </div>
    </header>
    <main class="main">
        <div class="container">
            <div class="main-style">
                <h1 class="h1-style">
                    Yo'nalishlar
                </h1>
                <div class="table-div">
                    <table class="table-style">
                        {% for direction in directions %}
                            <tr class="tr-style">
                                <td>
                                    {{ direction.direction_name }}
                                </td>
                                <td>
                                    <a href="{% url 'main:places' pk=direction.pk %}">
                                        <button class="button-style">
                                            Ma'lumotlar
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/faculties.html
{% extends 'base.html' %}

{% load static %}

{% block detail %}


    <header class="header">
        <div class="container">
            <div class="navbar">
                <div class="navbar-logo">
                    <img class="img-style" src="{% static 'img/logo.svg' %}" alt="#">
                    <h1 class="logo-h1"><a href="{% url 'main:faculties' %}">"TIQXMMI" MTU</a></h1>
                </div>
                <a class="a-style pc-media" href="{% url 'main:admin' %}">
                    <button class="button-style pc-media">
                        Admin
                    </button>
                </a>
            </div>
        </div>
    </header>
    <main class="main">
        <div class="container">
            <div class="main-style">
                <h1 class="h1-style">
                    Fakultetlar
                </h1>
                <div class="table-div">
                    <table class="table-style">
                        {% for faculty in faculties %}
                            <tr class="tr-style">
                                <td>
                                    {{ faculty.faculty_name }}
                                </td>
                                <td>
                                    <a href="{% url 'main:departments' pk=faculty.pk %}">
                                        <button class="button-style">
                                            Ma'lumotlar
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/faculty_create.html
{% extends 'base.html' %}

{% load static %}

{% block detail %}

    <form class="form" method="post">
        {% csrf_token %}
        <div class="form__center">
            <h1 class="h1-style">Fakultet yaratish</h1>
            <div class="input-div">
                <label class="label-style">Fakultet yaratish
                    <input class="input-style" type="text" name="faculty_name" required>
                </label>
                <label class="label-style">Qisqartma
                    <input class="input-style" type="text" name="abbreviation">
                </label>
            </div>


            <div class="button-div_register">
                <a href="{% url 'main:admin' %}">
                    <button class="button-style" type="button">
                        Orqaga
                    </button>
                </a>
                <button class="button-style" type="submit">
                    Yaratish
                </button>
            </div>
        </div>
    </form>
{% endblock %}

templates/group_create.html
{% extends 'base.html' %}

{% load static %}

{% block detail %}

    <form class="form" method="post">
        {% csrf_token %}
        <div class="form__center">
            <h1 class="h1-style">Guruh Yaratish</h1>
            <div class="input-div">
                <label class="label-style">Guruh Raqami:
                    <input class="input-style" type="text" name="number" id="number" required>
                </label>
                <label>Yo'nalish:
                    <select class="input-style" id="direction" name="direction" required>
                        {% for direction in directions %}
                            <option class="option" value="{{ direction.id }}">{{ direction.direction_name }}</option>
                        {% endfor %}
                    </select>
                </label>
            </div>


            <div class="button-div_register">
                <a href="{% url 'main:admin' %}">
                    <button class="button-style" type="button">
                        Orqaga
                    </button>
                </a>
                <button class="button-style" type="submit">
                    Yaratish
                </button>
            </div>
        </div>
    </form>
{% endblock %}

templates/practice_create.html
{% extends 'base.html' %}

{% load static %}

{% block detail %}

    <form class="form" method="post">
        {% csrf_token %}
        <div class="form__center">
            <h1 class="h1-style">Amaliyot joyini yaratish</h1>
            <div class="input-div">
                <label class="label-style">Korxona nomi:
                    <input class="input-style" type="text" name="name" id="name" required>
                </label>
                <label class="label-style">Qisqartmasi:
                    <input class="input-style" type="text" name="abbreviation" id="abbreviation">
                </label>
                <label class="label-style">Telefon raqami
                    <input class="input-style" type="number" name="phone_number" id="phone_number" required>
                </label>
                <!-- limit -->
                <label class="label-style">Limit
                    <input class="input-style" type="number" name="limit" id="limit" required>
                </label>
                <label class="label-style">Manzil:
                    <textarea class="textarea-style" cols="30" rows="3" name="address" id="address" required></textarea>
                </label>
                <label class="label-style">Mo'ljal
                    <input class="input-style" type="text" name="target" id="target" required>
                </label>

                <label class="label-style">Yo'nalish:
                    <select class="input-style" id="direction" name="direction" required>
                        {% for direction in directions %}
                            <option class="option" value="{{ direction.id }}">{{ direction.direction_name }}</option>
                        {% endfor %}
                    </select>
                </label>
            </div>


            <div class="button-div_register">
                <a href="{% url 'main:admin' %}">
                    <button class="button-style" type="button">
                        Orqaga
                    </button>
                </a>
                <button class="button-style" type="submit">
                    Yaratish
                </button>
            </div>
        </div>
    </form>

{% endblock %}

templates/practice_place.html
{% extends 'base.html' %}

{% load static %}

{% block detail %}

    <header class="header">
        <div class="container">
            <div class="navbar">
                <div class="navbar-logo">
                    <img class="img-style" src="{% static 'img/logo.svg' %}" alt="#">
                    <h1 class="logo-h1"><a href="{% url 'main:faculties' %}">"TIQXMMI" MTU</a></h1>
                </div>
                <a class="a-style pc-media" href="{% url 'main:export-data' pk=object.pk %}">
                    <button class="button-style pc-media">
                        Yuklab olish
                    </button>
                </a>
            </div>
        </div>
    </header>
    <main class="main">
        <div class="container">
            <div class="main-style">
                <div class="download-style">
                    <h1 class="h1-style">
                        {{ object.name }}
                    </h1>
                </div>
                <div class="table-div">
                    <table class="table-style">
                        {% for user in users %}
                            <tr class="tr-style tr-style_name tr-style_left">
                            <td>
                                {{ user.last_name }}
                            </td>
                            <td class="td-style">
                                {{ user.first_name }}
                            </td>
                            <td>
                                {{ user.group.number }}
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/practice_places.html
{% extends 'base.html' %}

{% load static %}

{% block detail %}
    <header class="header">
        <div class="container">
            <div class="navbar">
                <div class="navbar-logo">
                    <img class="img-style" src="{% static 'img/logo.svg' %}" alt="#">
                    <h1 class="logo-h1"><a href="{% url 'main:faculties' %}">"TIQXMMI" MTU</a></h1>
                </div>
            </div>
        </div>
    </header>
    <main class="main">
        <div class="container">
            <div class="main-style">
                <h1 class="h1-style">
                    Amaliyot joylari
                </h1>
                <div class="table-div">
                    <table class="table-style">
                        {% for place in places %}
                            <tr class="tr-style">
                                <td>
                                    {{ place.name }}
                                </td>
                                <td>
                                    <a href="{% url 'main:users' pk=place.pk %}">
                                        <button class="button-style">
                                            Ma'lumotlar
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% load static %}

{% block detail %}
    <div class="content">
        {% if limit_reached %}
            <div id="limit-reached-alert" class="alert alert-danger" role="alert">
                <span class="close-btn" onclick="this.parentElement.style.display='none';">&times;</span>
                Amaliyot joylari uchun foydalanuvchi chegarasiga yetdi. Siz buni tanlay olmaysiz
            </div>
        {% endif %}


        <form class="form" id="user-registration-form" method="POST" action="">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="form__center register-form">
                <h1 class="h1-style h1-style_grid">Registratsiya</h1>
                <div class="form-group">
                    <label for="id_first_name">Ism:
                        <input class="input-style" type="text" name="first_name">
                    </label>
                </div>
                <div class="form-group">
                    <label for="id_last_name">Familiya:
                        <input class="input-style" type="text" name="last_name">
                    </label>
                </div>
                <div class="form-group">
                    <label for="id_faculty">Fakultet:</label>
                    <select class="input-style" name="faculty" id="id_faculty">
                        <option value="">Fakultet tanlang</option>
                        {% for faculty in faculties %}
                            <option value="{{ faculty.id }}">{{ faculty.faculty_name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="id_department">Kafedra:</label>
                    <select class="input-style" name="department" id="id_department"></select>
                </div>
                <div class="form-group">
                    <label for="id_direction">Yo'nalish:</label>
                    <select class="input-style" name="direction" id="id_direction"></select>
                </div>
                <div class="form-group">
                    <label for="id_practice_place">Amaliyot joyi:</label>
                    <select class="input-style" name="practice_place" id="id_practice_place"></select>
                </div>
                <div class="form-group">
                    <label for="id_group">Guruh:</label>
                    <select class="input-style" name="group" id="id_group"></select>
                </div>
                <div class="button-div">
                    <a href="#">
                        <button class="button-style" type="submit">
                            Orqaga
                        </button>
                    </a>
                    <button class="button-style button-style_grid" type="submit">
                        Registratsiya
                    </button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}
{% block extra_js %}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        setTimeout(function () {
            document.getElementById('limit-reached-alert').style.display = 'none';
        }, 15000);
    </script>
    <script>
        $(document).ready(function () {
            console.log('jQuery version:', $.fn.jquery);
            $('#id_faculty').change(function () {
                var facultyId = $(this).val();
                console.log('Faculty_id:', facultyId);
                $.get('/uz/main/get_departments/', {faculty_id: facultyId}, function (data) {
                    console.log('Received departments:', data);
                    $('#id_department').empty();
                    $('#id_department').append($('<option>').text('Select Department').attr('value', ''));
                    $.each(data.departments, function (index, department) {
                        $('#id_department').append($('<option>').text(department.name).attr('value', department.id));
                    });
                });
            });

            $('#id_department').change(function () {
                var departmentId = $(this).val();
                $.get('/uz/main/get_directions/', {department_id: departmentId}, function (data) {
                    $('#id_direction').empty();
                    $('#id_direction').append($('<option>').text('Select Direction').attr('value', ''));
                    $.each(data.directions, function (index, direction) {
                        $('#id_direction').append($('<option>').text(direction.name).attr('value', direction.id));
                    });
                });
            });

            $('#id_direction').change(function () {
                var directionId = $(this).val();
                $.get('/uz/main/get_practice_places/', {direction_id: directionId}, function (data) {
                    $('#id_practice_place').empty();
                    $('#id_practice_place').append($('<option>').text('Select Practice Place').attr('value', ''));
                    $.each(data.practice_places, function (index, place) {
                        $('#id_practice_place').append($('<option>').text(place.name).attr('value', place.id));
                    });
                });

                $.get('/uz/main/get_groups/', {direction_id: directionId}, function (data) {
                    $('#id_group').empty();
                    $('#id_group').append($('<option>').text('Select Group').attr('value', ''));
                    $.each(data.groups, function (index, group) {
                        $('#id_group').append($('<option>').text(group.name).attr('value', group.id));
                    });
                });
            });
        });
    </script>
{% endblock %}